#
# As a design choice, each dexcom user gets a separate set of
# prometheus rules: This allows them to have individual settings for
# reporting problems.
#
# This also has the nice side effect of reducing the amount of
# templating needed in the alerts - Go's template syntax is cumbersome
# in Helm charts.
#
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ include "dexcom-exporter.fullname" . }}
  labels:
    {{- include "dexcom-exporter.labels" . | nindent 4 }}
spec:
  groups:

    - name: dexcom
      rules:

        # - alert: NoBloodSugarData
        #   annotations:
        #     summary: No blood sugar data is being received for {{ .Values.dexcom.username }}
        #     description: |
        #       This may be down to a problem with the sensor (they have
        #       expiry dates), the bluetooth connection, the user's
        #       phone, the user's internet connection, Dexcom's systems
        #       or even the prometheus exporter itself.

        #       Without this data, problems cannot be detected, and no
        #       alerts will be sent.
        #   expr: |
        #     absent(up{job="dexcom-exporter", dexcom_username="{{.Values.dexcom.username}}"}[10m:1m]) == 1
        #   {{- with .Values.rules.noData.for }}
        #   for: {{ . }}
        #   {{- end }}
        #   labels:
        #     severity: error

        - alert: BloodSugarLevelLow
          annotations:
            summary: Blood sugar level is critically low for {{ .Values.dexcom.username }}
            description: >-
              {{ .Values.dexcom.username }} has critically low blood sugar level
              (currently {{"{{"}} printf "%.1f" $value {{"}}"}} mmol/ltr)
              and may need help.

              Very low blood sugar can cause confusion, cognitive
              difficulties or even seizures, which can prevent the
              sufferer from dealing with the issue themselves.

            action: Need to urgently eat something or even administer a glucose injection
          expr: |
            last_over_time(glucose_mmol{job="dexcom-exporter", dexcom_username="{{.Values.dexcom.username}}"}[10m])
            < {{ .Values.rules.criticalLow.mmolLtr }}
          {{- with .Values.rules.criticalLow.for }}
          for: {{ . }}
          {{- end }}
          labels:
            severity: critical
            action: needsGlucose

        - alert: BloodSugarLevelLow
          annotations:
            summary: Blood sugar level is low for {{ .Values.dexcom.username }}
            description: >-
              {{ .Values.dexcom.username }} has a low blood sugar level
              (currently {{"{{"}} printf "%.1f" $value{{"}}" }} mmol/ltr)
              - if it drops much lower he/she may need help.

            action: Need to eat something to bring blood sugar level up
          expr: |
            last_over_time(glucose_mmol{job="dexcom-exporter", dexcom_username="{{.Values.dexcom.username}}"}[10m])
            < {{ .Values.rules.low.mmolLtr }}
          {{- with .Values.rules.low.for }}
          for: {{ . }}
          {{- end }}
          labels:
            severity: warning
            action: needsGlucose

        # No alerts for levels between "low" and "high" - these are the _desired_ values!

        - alert: BloodSugarLevelHigh
          annotations:
            summary: Blood sugar level is high for {{ .Values.dexcom.username }}
            description: >-
              {{ .Values.dexcom.username }} has a high blood sugar level
              (currently {{"{{"}} printf "%.1f" $value {{"}}"}} mmol/ltr),
              and may need insulin.

            action: Ensure that insulin has been administered
          expr: |
            last_over_time(glucose_mmol{job="dexcom-exporter", dexcom_username="{{.Values.dexcom.username}}"}[10m])
            >= {{ .Values.rules.high.mmolLtr }}
          {{- with .Values.rules.high.for }}
          for: {{ . }}
          {{- end }}
          labels:
            severity: warning
            action: needsInsulin

        - alert: BloodSugarLevelHigh
          annotations:
            summary: Blood sugar level is very high for {{ .Values.dexcom.username }}
            description: >-
              {{ .Values.dexcom.username }} has a high blood sugar level
              (currently {{"{{"}} printf "%.1f" $value {{"}}"}} mmol/ltr),
              and likely needs insulin.

              It is normal for blood sugar levels to spike after a
              meal, but prolonged periods of high blood sugar levels
              can lead to long term health problems.

              Perhaps insulin was not administered?
            action: Need to administer insulin - urgently
          expr: |
            last_over_time(glucose_mmol{job="dexcom-exporter", dexcom_username="{{.Values.dexcom.username}}"}[10m])
            >= {{ .Values.rules.veryHigh.mmolLtr }}
          {{- with .Values.rules.veryHigh.for }}
          for: {{ . }}
          {{- end }}
          labels:
            severity: critical
            action: needsInsulin
