apiVersion: v1
kind: Secret
metadata:
  name: {{ include "dexcom-exporter.fullname" . }}
  labels:
    {{- include "dexcom-exporter.labels" . | nindent 4 }}
type: dexcom/creds
data:
  username: {{ .Values.dexcom.username | b64enc }}
  password: {{ .Values.dexcom.password | b64enc }}
