apiVersion: v1
kind: Secret
metadata:
  name: {{ include "dexcom-exporter.fullname" . }}
  labels:
    {{- include "dexcom-exporter.labels" . | nindent 4 }}
type: dexcom/creds
data:
  username: {{ required "dexcom.username must be specified" .Values.dexcom.username | b64enc }}
  password: {{ required "dexcom.password must be specified" .Values.dexcom.password | b64enc }}
