{{- if true }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "dexcom-exporter.fullname" . }}
  labels:
    {{- include "dexcom-exporter.labels" . | nindent 4 }}
spec:
  endpoints:
    - scheme: http
      filterRunning: true
      port: http
      path: /
      interval: {{ .Values.scrape.interval }}
      scrapeTimeout: {{ .Values.scrape.timeout }}
      targetPort: {{ .Values.service.port }}
      honorTimestamps: true
  jobLabel: dexcom-exporter
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  targetLabels:
    - dexcom.eu/username
    - dexcom/username
  selector:
    matchLabels:
      {{- include "dexcom-exporter.selectorLabels" . | nindent 6 }}
{{- end }}
