# Default values for dexcom-exporter.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# This will set the replicaset count more information can be found here: https://kubernetes.io/docs/concepts/workloads/controllers/replicaset/
replicaCount: 1

# This sets the container image more information can be found here: https://kubernetes.io/docs/concepts/containers/images/
image:
  repository: registry.home.jorgensen.org.uk/dexcom-dashboard
  # This sets the pull policy for images.
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

# This is for the secrets for pulling an image from a private repository more information can be found here: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
imagePullSecrets: []
# This is to override the chart name.
nameOverride: ""
fullnameOverride: ""

# This is for setting Kubernetes Annotations to a Pod.
# For more information checkout: https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/
podAnnotations: {}
# This is for setting Kubernetes Labels to a Pod.
# For more information checkout: https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/
podLabels: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

# This is for setting up a service more information can be found here: https://kubernetes.io/docs/concepts/services-networking/service/
service:
  # This sets the service type more information can be found here: https://kubernetes.io/docs/concepts/services-networking/service/#publishing-services-service-types
  type: ClusterIP
  # This sets the ports more information can be found here: https://kubernetes.io/docs/concepts/services-networking/service/#field-spec-ports
  port: 8000
  annotations: {}

# This block is for setting up the ingress for more information can be found here: https://kubernetes.io/docs/concepts/services-networking/ingress/
ingress:
  enabled: false
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

# This is to setup the liveness and readiness probes more information can be found here: https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/
livenessProbe: {}
  # httpGet:
  #   path: /
  #   port: http
readinessProbe: {}
  # httpGet:
  #   path: /
  #   port: http

# This section is for setting up autoscaling more information can be found here: https://kubernetes.io/docs/concepts/workloads/autoscaling/
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

# Additional volumes on the output Deployment definition.
volumes: []
# - name: foo
#   secret:
#     secretName: mysecret
#     optional: false

# Additional volumeMounts on the output Deployment definition.
volumeMounts: []
# - name: foo
#   mountPath: "/etc/foo"
#   readOnly: true

nodeSelector: {}

tolerations: []

affinity: {}

priorityClassName: ""

dexcom:
  username: ""
  password: ""
  region: us

scrape:
  # Interval between querying the Dexcom API.
  #
  # The Dexcom API appears to only collect data once every 5 minute, so
  # scraping much more frequently than this is probably useless.
  interval: 1m

  timeout: 30s


# Values for the prometheus rules.
#
# NOTE: There is only support specifying blood sugar in the molar
#       concentration where the level is specified in units of
#       mmol/Ltr.
#
# If you work in mass concentration (i.e. in units of mg/dL), then you
# must perform the conversion yourself. There are sources online for
# this e.g.:
#
#  * https://www.ncbi.nlm.nih.gov/books/NBK348987/ (check "TABLE 86")
#
#  * https://www.diabetes.co.uk/blood-sugar-converter.html
#
# There seems to be no general consensous on which values to use for
# the `priority` value for the severity.
#
rules:
  noData:
    severity: error
    for: 10m

  criticalLow:
    # Alert will fire below this value
    mmolLtr: 2.8
    severity: critical
    for: "" # fire immediately

  low:
    # Alert will fire below this value
    mmolLtr: 4.0
    severity: critical
    for: 5m

  high:
    # Alert will fire at or above this value
    mmolLtr: 7.0
    severity: warning
    # Longer grace period to allow for spikes after meals
    for: 30m

  veryHigh:
    # Alert will fire at or above this value
    mmolLtr: 11
    severity: error
    for: 20m

  criticalHigh:
    # Alert will fire at or above this value
    mmolLtr: 18
    severity: critical
    for: 10m
